### ISSUE TITLE
[1.16] Crash with 36.0.1 forge on multiplayer server and single player

### ISSUE THREAD

**Issue by Letoric** [InnovativeOnlineIndustries/Industrial-Foregoing#963] opened 2021-01-18 18:01 UTC
[18Jan2021 11:46:03.581] [main/WARN] [net.minecraft.server.Main/]: Failed to load datapacks, can't proceed with server load. You can either fix your datapacks or reset to vanilla with --safeMode
java.util.concurrent.ExecutionException: java.lang.IllegalStateException: Missing required tags: minecraft:fluid:forge:milk
	at java.util.concurrent.CompletableFuture.reportGet(Unknown Source) ~[?:1.8.0_261]
	at java.util.concurrent.CompletableFuture.get(Unknown Source) ~[?:1.8.0_261]
	at net.minecraft.server.Main.main(Main.java:130) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_261]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_261]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_261]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_261]
	at net.minecraftforge.fml.loading.FMLServerLaunchProvider.lambda$launchService$0(FMLServerLaunchProvider.java:51) ~[forge-1.16.5-36.0.1.jar:36.0]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.9.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.9.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.9.jar:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.9.jar:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.9.jar:?]
	at net.minecraftforge.server.ServerMain$Runner.runLauncher(ServerMain.java:63) [forge-1.16.5-36.0.1.jar:?]
	at net.minecraftforge.server.ServerMain$Runner.access$100(ServerMain.java:60) [forge-1.16.5-36.0.1.jar:?]
	at net.minecraftforge.server.ServerMain.main(ServerMain.java:57) [forge-1.16.5-36.0.1.jar:?]
Caused by: java.lang.IllegalStateException: Missing required tags: minecraft:fluid:forge:milk
	at net.minecraft.tags.NetworkTagManager.lambda$reload$1(NetworkTagManager.java:47) ~[?:?]
	at java.util.concurrent.CompletableFuture.uniAccept(Unknown Source) ~[?:1.8.0_261]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(Unknown Source) ~[?:1.8.0_261]
	at java.util.concurrent.CompletableFuture$Completion.run(Unknown Source) ~[?:1.8.0_261]
	at net.minecraft.resources.AsyncReloader.func_219557_a(SourceFile:71) ~[?:?]
	at net.minecraft.resources.AsyncReloader.func_219560_a(SourceFile:70) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniCompletion.claim(Unknown Source) ~[?:1.8.0_261]
	at java.util.concurrent.CompletableFuture.uniAccept(Unknown Source) ~[?:1.8.0_261]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(Unknown Source) ~[?:1.8.0_261]
	at java.util.concurrent.CompletableFuture.postComplete(Unknown Source) ~[?:1.8.0_261]
	at java.util.concurrent.CompletableFuture.complete(Unknown Source) ~[?:1.8.0_261]
	at net.minecraft.resources.AsyncReloader$1.func_216873_a(SourceFile:53) ~[?:?]
	at net.minecraft.resources.AsyncReloader$1.func_216872_a(SourceFile:50) ~[?:?]
	at java.util.concurrent.CompletableFuture.uniCompose(Unknown Source) ~[?:1.8.0_261]
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(Unknown Source) ~[?:1.8.0_261]
	at java.util.concurrent.CompletableFuture.postComplete(Unknown Source) ~[?:1.8.0_261]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(Unknown Source) ~[?:1.8.0_261]
	at java.util.concurrent.CompletableFuture$AsyncSupply.exec(Unknown Source) ~[?:1.8.0_261]
	at java.util.concurrent.ForkJoinTask.doExec(Unknown Source) ~[?:1.8.0_261]
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(Unknown Source) ~[?:1.8.0_261]
	at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source) ~[?:1.8.0_261]
	at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source) ~[?:1.8.0_261]

Not 100% if this is you, or forge, given the change notes for 36.0.1, but posting here first.

**Comment by Letoric** [comment] 2021-01-18 18:02
IF Version is industrial-foregoing-1.16.4-3.2.8.3-7ac4a96

**Comment by ChloeDawn** [comment] 2021-01-19 00:34
I think this is caused by https://github.com/MinecraftForge/MinecraftForge/pull/7294 changing the tag type to whatever that optional stuff is, unsure.

**Comment by Buuz135** [comment] 2021-01-19 16:42
Fixed in #968

**Closed by Buuz135** 2021-01-19 16:42 UTC
Labels: type: bug, version: 1.16
