### ISSUE TITLE
[1.15] Conveyor Belt crash OR Right click with modded item/block Crashes Game

### ISSUE THREAD

**Issue by BriqzTM** [InnovativeOnlineIndustries/Industrial-Foregoing#773] opened 2020-05-31 23:00 UTC
I just got into modded Minecraft and thought this mod looked awesome to learn, but messing with the items I placed a conveyor belt and click the belt with the conveyor belt addons. How can I fix? 

EDIT: Anytime I right click one mod item/block with another, then it automatically crashes. Maybe not specific to the belts. 

**Industrial Foregoing Version:**
indusrial foregoing mod 1.15-2.3.0
**Titanium Version:**
titanium- 1.15.2 - 2.4.0

**Crashlog If Applicable (Upload to pastebin/gist):**
The game crashed whilst unexpected error
Error: java.lang.NoClassDefFoundError: mezz/jei/api/gui/handlers/IGhostIngredientHandler$Target

**Comment by Buuz135** [comment] 2020-06-14 18:20
Duplicate of #773

**Closed by Buuz135** 2020-06-14 18:20 UTC
Labels: type: bug, version: 1.15
