### ISSUE TITLE
[1.16] Forge 32.0.90+ breaks your mod

### ISSUE THREAD

**Issue by 04Slash** [InnovativeOnlineIndustries/Industrial-Foregoing#810] opened 2020-07-28 23:21 UTC
**Industrial Foregoing Version:** industrial-foregoing-1.16.1-3.0.3-5935836.jar

**Titanium Version:** titanium-1.16.1-3.0.2.jar

**Crashlog If Applicable (Upload to pastebin/gist):** No crash report. [Latest.log](https://pastebin.com/BkspH3FQ)

[Error screen](https://imgur.com/cRavEbL)
**No other mods are present**
The game will load just fine with forge 32.0.86-88.
Using forge 32.0.90-92 will cause the game to instantly close. No useful information in the latest.log, and no crash report.
Using the previous version of IE (106) will have the same results with the above forge versions.

Going to post this so people who actually use google can find this, so please ignore:
Failed to create mod instance. ModID: titanium, class com.hrznstudio.titanium.Titanium
java.lang.IllegalArgumentException: Cannot register a generic event listener with addListener, use addGenericListener

Update: While searching for other mods, this seems to be an issue with forge and not your mod.
Update 2: Jumped the gun a little too soon. This mod is still broken with forge 32.0.96. I will leave this open for now seeing as it's still an issue. You can feel free to close if you desire, seeing as this (probably) isn't an issue with your mod.
**If anyone has this issue, downgrading forge to 32.0.88 will fix this.**

P.S. Portality is also broken with the same issue.

**Comment by North-West-Wind** [comment] 2020-07-29 11:17
I guess I can confirm that it is the issue of Forge itself as Pam's Harvest Craft 2 Food Core is also broken with the same thing.

**Comment by Gbergz** [comment] 2020-07-29 12:19
Can confirm this is because of forge's breaking changes in the latest updates. .88 still works. Staying with that for awhile.

**Comment by SDUBZ** [comment] 2020-07-30 03:30
same here https://gist.github.com/SDUBZ/57917fcdc96d45b82285dd58daacc172

**Comment by Buuz135** [comment] 2020-08-01 17:28
Fixed in https://github.com/InnovativeOnlineIndustries/Industrial-Foregoing/commit/5bc4010fde810a56b1cecf92099143ec32c7e830

**Closed by Buuz135** 2020-08-01 17:28 UTC
Labels: type: bug, version: 1.16
