### ISSUE TITLE
Potion Brewer Crash

### ISSUE THREAD

**Issue by Zolgia** [InnovativeOnlineIndustries/Industrial-Foregoing#611] opened 2019-09-27 18:30 UTC
https://paste.dimdev.org/lotarirobe.mccrash

Just encountered this playing Stoneblock 2. I was pumping water bottles into it from the left side. It used the 4 inventories at the top, leaving the leftmost one empty. The 5th water bottle entered the the potion brewer and went into the leftmost top spot then crashed the game. Whenever I try to enter my world it automatically crashes now, if that helps.

**Comment by TheCodedOne** [comment] 2019-09-27 18:31
Duplicate of #413

**Closed by TheCodedOne** 2019-09-27 18:31 UTC
