### ISSUE TITLE
[1.16] Leaf Shearing Addon Missing

### ISSUE THREAD

**Issue by quasarea** [InnovativeOnlineIndustries/Industrial-Foregoing#979] opened 2021-01-27 19:23 UTC
**Industrial Foregoing Version:**
industrial-foregoing-1.16.4-3.2.7-7d95990

**Titanium Version:**
titanium-1.16.4-3.2.4

As @Insomnik pointed out in Discussion https://github.com/InnovativeOnlineIndustries/Industrial-Foregoing/discussions/876 there is no leaf-shearing addon. Is this intender, or is this a bug?

**Comment by Buuz135** [comment] 2021-01-27 19:26
Duplicate of #876

**Closed by Buuz135** 2021-01-27 19:26 UTC
Labels: type: bug, version: 1.16

**Comment by quasarea** [comment] 2021-01-31 12:36
@Buuz135 can't answer ?:(

**Comment by Buuz135** [comment] 2021-01-31 12:53
Its not implemented yet that why its a feature request ...
