### ISSUE TITLE
Loading a bottle of water into a Potion Brewer's tank/top slot crashes the game

### ISSUE THREAD

**Issue by HeyWhatsHisFace** [InnovativeOnlineIndustries/Industrial-Foregoing#592] opened 2019-08-06 10:21 UTC
Mod Pack: Sky Factory 4
Industrial Foregoing Version: 1.12.12 
TeslaCoreLib Version: 1.12.2-1.0.15
Description: Ticking block entity

![2019-08-06_05 01 41](https://user-images.githubusercontent.com/53689986/62532094-4f876300-b809-11e9-8b88-3dbc854506d5.png)

![Screenshot_1046](https://user-images.githubusercontent.com/53689986/62532075-439ba100-b809-11e9-87e7-73bc5c4400e6.png)

```
java.lang.NullPointerException: Ticking block entity
	at net.ndrei.teslacorelib.utils.FluidUtils.fillFluidFrom(FluidUtils.kt:60)
	at net.ndrei.teslacorelib.utils.FluidextensionsKt.fillFrom(fluidextensions.kt:16)
	at net.ndrei.teslacorelib.utils.FluidextensionsKt.fillFrom(fluidextensions.kt:22)
	at net.ndrei.teslacorelib.utils.FluidextensionsKt.processInputInventory(fluidextensions.kt:27)
	at net.ndrei.teslacorelib.tileentities.SidedTileEntity.processFluidItems(SidedTileEntity.kt:544)
	at net.ndrei.teslacorelib.tileentities.SidedTileEntity.processImmediateInventories(SidedTileEntity.kt:214)
	at net.ndrei.teslacorelib.tileentities.ElectricMachine.processImmediateInventories(ElectricMachine.kt:298)
	at net.ndrei.teslacorelib.tileentities.SidedTileEntity.func_73660_a(SidedTileEntity.kt:992)
	at net.minecraft.world.World.func_72939_s(World.java:1835)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:252)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Unknown Source)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at net.ndrei.teslacorelib.utils.FluidUtils.fillFluidFrom(FluidUtils.kt:60)
	at net.ndrei.teslacorelib.utils.FluidextensionsKt.fillFrom(fluidextensions.kt:16)
	at net.ndrei.teslacorelib.utils.FluidextensionsKt.fillFrom(fluidextensions.kt:22)
	at net.ndrei.teslacorelib.utils.FluidextensionsKt.processInputInventory(fluidextensions.kt:27)
	at net.ndrei.teslacorelib.tileentities.SidedTileEntity.processFluidItems(SidedTileEntity.kt:544)
	at net.ndrei.teslacorelib.tileentities.SidedTileEntity.processImmediateInventories(SidedTileEntity.kt:214)
	at net.ndrei.teslacorelib.tileentities.ElectricMachine.processImmediateInventories(ElectricMachine.kt:298)
	at net.ndrei.teslacorelib.tileentities.SidedTileEntity.func_73660_a(SidedTileEntity.kt:992)

-- Block entity being ticked --
Details:
	Name: industrialforegoing:potion_enervator_tile // com.buuz135.industrial.tile.magic.PotionEnervatorTile
	Block type: ID #2633 (tile.industrialforegoing.potion_enervator // com.buuz135.industrial.tile.block.PotionEnervatorBlock // industrialforegoing:potion_enervator)
	Block data value: 3 / 0x3 / 0b0011
	Block location: World: (3,71,1), Chunk: (at 3,4,1 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Actual block type: ID #2633 (tile.industrialforegoing.potion_enervator // com.buuz135.industrial.tile.block.PotionEnervatorBlock // industrialforegoing:potion_enervator)

```

**Comment by minakitty** [comment] 2019-11-14 11:24
looks like the same issue in #413 ... I had EnderCore installed and the tweak of changing it's config for how it handled fluids worked

**Comment by TheCodedOne** [comment] 2019-11-14 11:33
Duplicate of #413

**Closed by TheCodedOne** 2019-11-14 11:33 UTC
