### ISSUE TITLE
Strange crash when placing a water bottle into a Froster

### ISSUE THREAD

**Issue by BlackjackMKV** [InnovativeOnlineIndustries/Industrial-Foregoing#484] opened 2018-12-31 08:02 UTC
Industrial Foregoing Version: 1.12.2-1.12.3-227
TeslaCoreLib Version: 1.0.15
Crashlog (If Any):
Part 1(https://pastebin.com/QGY4cNNd)
Part 2(https://pastebin.com/L98iH8Fk)

This crash occurs whenever one tries to feed the Froster a water bottle instead of a bucket. Not sure why.

**Comment by TheCodedOne** [comment] 2018-12-31 09:01
Can you post the crash report which will be in the crash reports folder, not the game logs

**Comment by BlackjackMKV** [comment] 2018-12-31 09:12
Ah, my bad. Here's the crash report as well. https://pastebin.com/qHje01Zm

On the bright side, a little more data from the game logs couldn't hurt at least. :P

**Comment by Routhinator** [comment] 2019-03-20 21:15
@TheCodedOne  this is caused by a coding error in TeslaCoreLib

https://github.com/MinecraftModDevelopmentMods/Tesla-Core-Lib/issues/28 

Not sure when it will be fixed.

Only way to work around it for now is turning off the water bottles as fluid contianers option in EnderCore

Same error as this: https://github.com/Buuz135/Industrial-Foregoing/issues/413

**Comment by TheCodedOne** [comment] 2019-03-20 23:19
I'm aware.

**Comment by Buuz135** [comment] 2020-12-27 19:15
:wave: Sorry but Industrial Foregoing has ended support for version 1.12. I'm closing this issue as it will no longer be updated for that version. Thanks for playing with the mod.

**Closed by Buuz135** 2020-12-27 19:15 UTC
Labels: extra: info required, not supported, type: bug, version: 1.12
