### ISSUE TITLE
Client side NPE with potion_enervator

### ISSUE THREAD

**Issue by LemADEC** [InnovativeOnlineIndustries/Industrial-Foregoing#413] opened 2018-08-14 20:54 UTC
Industrial Foregoing Version: industrialforegoing-1.12.2-1.10.6-192.jar
TeslaCoreLib Version: tesla-core-lib-1.12.2-1.0.15.jar
(as part of Direwolf20 1.12-2.2.0
Crashlog (If Any): https://gist.github.com/LemADEC/029c3e2a388c62a6aa5ef72af860549e
```
java.lang.NullPointerException: Ticking block entity
	at net.ndrei.teslacorelib.utils.FluidUtils.fillFluidFrom(FluidUtils.kt:60)
	at net.ndrei.teslacorelib.utils.FluidextensionsKt.fillFrom(fluidextensions.kt:16)
	at net.ndrei.teslacorelib.utils.FluidextensionsKt.fillFrom(fluidextensions.kt:22)
	at net.ndrei.teslacorelib.utils.FluidextensionsKt.processInputInventory(fluidextensions.kt:27)
	at net.ndrei.teslacorelib.tileentities.SidedTileEntity.processFluidItems(SidedTileEntity.kt:544)
	at net.ndrei.teslacorelib.tileentities.SidedTileEntity.processImmediateInventories(SidedTileEntity.kt:214)
	at net.ndrei.teslacorelib.tileentities.ElectricMachine.processImmediateInventories(ElectricMachine.kt:298)
	at net.ndrei.teslacorelib.tileentities.SidedTileEntity.func_73660_a(SidedTileEntity.kt:992)
	at net.minecraft.world.World.func_72939_s(World.java:1832)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1845)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1096)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
```

![image](https://user-images.githubusercontent.com/4776032/44117898-d8b47342-a014-11e8-9f9a-6a2a648bb81d.png)

**Comment by BrisingrAerowing** [comment] 2018-08-28 18:06
What were you using to fill the machine? I had a virtually identical crash with the Pressure Pipes canister some time ago.

**Comment by Shybella** [comment] 2018-09-19 20:48
![download](https://user-images.githubusercontent.com/4436776/45780575-6c8a6600-bc38-11e8-956b-63e079421201.png)

Report: https://pastebin.com/DAjxcJ24

Somehow he was able to place it in the slot.

**Comment by Slyklaw** [comment] 2019-01-13 11:19
This might be the bug I encountered. I put in a stack of Nether Wort, then I clicked the Water Bottle in the spot next to the Nether Wort as seen in the following screenshot. Game froze.

![potionbrewer](https://user-images.githubusercontent.com/44900062/51084592-100b0380-175f-11e9-88e3-f5f52080de58.png)

**Comment by BrisingrAerowing** [comment] 2019-01-13 17:43
@Slyklaw Do you have Ender Core? If you do, turn off the water bottles as fluid containers option in there. That option breaks more things than it helps.

**Comment by Slyklaw** [comment] 2019-01-13 23:54
@BrisingrAerowing Yup, that fixes my crash.

**Comment by BrisingrAerowing** [comment] 2019-01-14 03:54
Good to hear.

**Comment by krisjenner** [comment] 2019-05-09 15:59
Setting EnderCore option for water bottles to false doesn't fix this anymore, unfortunately

**Comment by BrisingrAerowing** [comment] 2019-05-09 19:24
@krisjenner which option did you disable? There’s two options related to bottles. Both may need to be turned off.

**Comment by krisjenner** [comment] 2019-05-10 09:23
@BrisingrAerowing My bad!! Didn't see the other option - disabled now and seems to work. Thanks :)

**Comment by nifker** [comment] 2019-12-11 16:54
I have the same issue when automatically crafting awkward potions.

**Comment by HenryLoenwind** [comment] 2020-05-02 16:16
https://github.com/MinecraftModDevelopmentMods/Tesla-Core-Lib/issues/28

Not caused by endercore.

**Comment by skelertron** [comment] 2020-11-27 17:29
I have just recently run into this issue in the Industrial Foregoing inclusion in the latest FTB Revelations pack, by manually inputting a water potion, same as author.

**Comment by ZiDeveloper** [comment] 2020-12-05 02:07
> @Slyklaw Do you have Ender Core? If you do, turn off the water bottles as fluid containers option in there. That option breaks more things than it helps.

This one fixed it!
(for people who need help with it)
1. Go to your **modpacks folder** and open the **config** folder
2. Open the **endercore** folder and edit **endercore.cfg** file
3. Search for **bottleFluidHandler**(CTRL+F) and edit it from **true** to **false** then save the file
4. Enjoy

**Comment by Buuz135** [comment] 2020-12-27 19:22
:wave: Sorry but Industrial Foregoing has ended support for version 1.12. I'm closing this issue as it will no longer be updated for that version. Thanks for playing with the mod.

**Closed by Buuz135** 2020-12-27 19:22 UTC
Labels: not supported, type: bug, type: other software, version: 1.12
